server:
  port: 8882
  shutdown: graceful
spring:
  application:
    name: service-hi
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: service-config
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 172.26.4.60
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
